import type { Locale } from '../i18n';

export interface GoPlanCampaignCopy {
  eyebrow: string;
  headline: string;
  description: string;
  benefit: string;
  status: string;
  cta: string;
  renewal: string;
  boundary: string;
  newBadge: string;
  closeAria: string;
  providersAria: string;
  workbenchBadge: string;
  workbenchBadgeAria: string;
}

const english: GoPlanCampaignCopy = {
  eyebrow: 'NEW PLAN · LAUNCH OFFER',
  headline: 'Low-cost design plan for everyone',
  description: 'Professional design intelligence at a lower cost—so every idea moves faster from prompt to finished work.',
  benefit: 'Go first month $5 · unlimited use',
  status: 'UNLIMITED',
  cta: 'View Go plan · Limited-time 50% off',
  renewal: 'Then $10 / month',
  boundary: 'Allowance details and offer terms are shown on Pricing.',
  newBadge: 'NEW',
  closeAria: 'Close dialog',
  providersAria: 'Model providers available on Go',
  workbenchBadge: 'The new Go Plan · ¥5 for the first month · Unlimited model usage',
  workbenchBadgeAria: 'The new Go Plan, ¥5 for the first month, unlimited model usage — view Pricing',
};

const localized: Record<Locale, GoPlanCampaignCopy> = {
  en: english,
  no: {
    eyebrow: 'NY PLAN · LANSERINGSTILBUD',
    headline: 'Møt Go: mer rom for å skape videre.',
    description: 'En lettere plan for hverdagens design og koding, med populære modeller klare til bruk.',
    benefit: 'Go første måned $5 · ubegrenset bruk',
    status: 'UBEGRENSET',
    cta: 'Se Go-planen',
    renewal: 'Deretter $10 / måned',
    boundary: 'Detaljer om kvoten og vilkårene for tilbudet vises på prissiden.',
    newBadge: 'NY',
    closeAria: 'Lukk dialogen',
    providersAria: 'Modellleverandører tilgjengelig i Go',
    workbenchBadge: 'Go første måned $5 · ubegrenset bruk',
    workbenchBadgeAria: 'Go første måned $5, ubegrenset bruk — se priser',
  },
  de: {
    eyebrow: 'NEUER TARIF · STARTANGEBOT',
    headline: 'Lerne Go kennen: mehr Freiraum, um kreativ zu bleiben.',
    description: 'Ein leichter Tarif für alltägliches Design und Coding, mit beliebten Modellen direkt einsatzbereit.',
    benefit: 'Go im ersten Monat $5 · unbegrenzte Nutzung',
    status: 'UNBEGRENZT',
    cta: 'Go-Tarif ansehen',
    renewal: 'Danach $10 / Monat',
    boundary: 'Kontingentdetails und Angebotsbedingungen stehen auf der Preisseite.',
    newBadge: 'NEU',
    closeAria: 'Dialog schließen',
    providersAria: 'In Go verfügbare Modellanbieter',
    workbenchBadge: 'Go: erster Monat $5 · unbegrenzt',
    workbenchBadgeAria: 'Go: erster Monat $5, unbegrenzte Nutzung — Preise ansehen',
  },
  'zh-CN': {
    eyebrow: '全新套餐 · 首发特惠',
    headline: '人人可用的低成本设计方案',
    description: '以更低成本使用专业设计模型，让每一个想法更快成为作品。',
    benefit: 'Go 首月 $5 · 无限用',
    status: '无限使用',
    cta: '查看 Go 套餐 · 限时 5 折',
    renewal: '之后 $10 / 月',
    boundary: '具体额度与活动规则以 Pricing 页面为准。',
    newBadge: 'NEW',
    closeAria: '关闭弹窗',
    providersAria: 'Go 套餐可用模型厂商',
    workbenchBadge: '全新 Go 套餐 · 首月 ¥5 · 模型无限用',
    workbenchBadgeAria: '全新 Go 套餐，首月 ¥5，模型无限用，查看 Pricing',
  },
  'pt-BR': {
    eyebrow: 'NOVO PLANO · OFERTA DE LANÇAMENTO',
    headline: 'Conheça o Go: mais espaço para continuar criando.',
    description: 'Um plano mais leve para design e programação do dia a dia, com modelos populares prontos para usar.',
    benefit: 'Go no primeiro mês por $5 · uso ilimitado',
    status: 'ILIMITADO',
    cta: 'Ver plano Go',
    renewal: 'Depois, $10 / mês',
    boundary: 'Os detalhes da franquia e os termos da oferta estão na página de preços.',
    newBadge: 'NOVO',
    closeAria: 'Fechar caixa de diálogo',
    providersAria: 'Provedores de modelos disponíveis no Go',
    workbenchBadge: 'Go no primeiro mês por $5 · uso ilimitado',
    workbenchBadgeAria: 'Go no primeiro mês por $5, uso ilimitado — ver preços',
  },
  'es-ES': {
    eyebrow: 'PLAN NUEVO · OFERTA DE LANZAMIENTO',
    headline: 'Conoce Go: más espacio para seguir creando.',
    description: 'Un plan más ligero para el diseño y la programación diarios, con modelos populares listos para usar.',
    benefit: 'Go el primer mes por $5 · uso ilimitado',
    status: 'ILIMITADO',
    cta: 'Ver el plan Go',
    renewal: 'Después, $10 / mes',
    boundary: 'Los detalles de la cuota y las condiciones de la oferta se muestran en la página de precios.',
    newBadge: 'NUEVO',
    closeAria: 'Cerrar diálogo',
    providersAria: 'Proveedores de modelos disponibles en Go',
    workbenchBadge: 'Go el primer mes por $5 · uso ilimitado',
    workbenchBadgeAria: 'Go el primer mes por $5, uso ilimitado — ver precios',
  },
  ar: {
    eyebrow: 'خطة جديدة · عرض الإطلاق',
    headline: 'تعرّف على Go: مساحة أكبر لمواصلة الإبداع.',
    description: 'خطة أخف للتصميم والبرمجة اليومية، مع نماذج شائعة جاهزة للاستخدام.',
    benefit: 'Go للشهر الأول مقابل 5 دولارات · استخدام غير محدود',
    status: 'غير محدود',
    cta: 'عرض خطة Go',
    renewal: 'ثم 10 دولارات / شهريًا',
    boundary: 'تظهر تفاصيل الحصة وشروط العرض في صفحة الأسعار.',
    newBadge: 'جديد',
    closeAria: 'إغلاق مربع الحوار',
    providersAria: 'موفرو النماذج المتاحون في Go',
    workbenchBadge: 'Go للشهر الأول مقابل 5 دولارات · استخدام غير محدود',
    workbenchBadgeAria: 'Go للشهر الأول مقابل 5 دولارات، استخدام غير محدود — عرض الأسعار',
  },
  ja: {
    eyebrow: '新プラン · ローンチ特典',
    headline: 'Goで、創作をもっと自由に。',
    description: '日々のデザインとコーディングに適した軽量プラン。人気モデルをすぐに使えます。',
    benefit: 'Go 初月 $5 · 無制限で利用',
    status: '無制限',
    cta: 'Goプランを見る',
    renewal: '以降 $10 / 月',
    boundary: '利用枠の詳細とキャンペーン条件は料金ページに表示されます。',
    newBadge: '新着',
    closeAria: 'ダイアログを閉じる',
    providersAria: 'Goで利用できるモデルプロバイダー',
    workbenchBadge: 'Go 初月 $5 · 無制限',
    workbenchBadgeAria: 'Go 初月 $5、無制限で利用 — 料金を見る',
  },
  ko: {
    eyebrow: '새 요금제 · 출시 혜택',
    headline: 'Go로 더 여유롭게 창작을 이어가세요.',
    description: '일상적인 디자인과 코딩을 위한 가벼운 요금제로, 인기 모델을 바로 사용할 수 있습니다.',
    benefit: 'Go 첫 달 $5 · 무제한 사용',
    status: '무제한',
    cta: 'Go 요금제 보기',
    renewal: '이후 월 $10',
    boundary: '사용량 세부 정보와 혜택 조건은 요금 페이지에서 확인할 수 있습니다.',
    newBadge: '신규',
    closeAria: '대화 상자 닫기',
    providersAria: 'Go에서 사용할 수 있는 모델 제공업체',
    workbenchBadge: 'Go 첫 달 $5 · 무제한',
    workbenchBadgeAria: 'Go 첫 달 $5, 무제한 사용 — 요금 보기',
  },
  fr: {
    eyebrow: 'NOUVELLE FORMULE · OFFRE DE LANCEMENT',
    headline: 'Découvrez Go : plus de liberté pour continuer à créer.',
    description: 'Une formule légère pour le design et le code au quotidien, avec des modèles populaires prêts à l’emploi.',
    benefit: 'Premier mois de Go à 5 $ · usage illimité',
    status: 'ILLIMITÉ',
    cta: 'Voir la formule Go',
    renewal: 'Puis 10 $ / mois',
    boundary: 'Les détails du quota et les conditions de l’offre figurent sur la page des tarifs.',
    newBadge: 'NOUVEAU',
    closeAria: 'Fermer la boîte de dialogue',
    providersAria: 'Fournisseurs de modèles disponibles avec Go',
    workbenchBadge: 'Go : premier mois à 5 $ · usage illimité',
    workbenchBadgeAria: 'Go : premier mois à 5 $, usage illimité — voir les tarifs',
  },
  it: {
    eyebrow: 'NUOVO PIANO · OFFERTA DI LANCIO',
    headline: 'Scopri Go: più spazio per continuare a creare.',
    description: 'Un piano più leggero per il design e la programmazione di ogni giorno, con modelli popolari pronti all’uso.',
    benefit: 'Go primo mese a $5 · uso illimitato',
    status: 'ILLIMITATO',
    cta: 'Vedi il piano Go',
    renewal: 'Poi $10 / mese',
    boundary: 'I dettagli della quota e le condizioni dell’offerta sono riportati nella pagina dei prezzi.',
    newBadge: 'NOVITÀ',
    closeAria: 'Chiudi finestra di dialogo',
    providersAria: 'Provider di modelli disponibili con Go',
    workbenchBadge: 'Go primo mese $5 · uso illimitato',
    workbenchBadgeAria: 'Go primo mese a $5, uso illimitato — vedi i prezzi',
  },
};

export function getGoPlanCampaignCopy(locale: Locale): GoPlanCampaignCopy {
  return localized[locale];
}
